# Generated by Django 5.0.4 on 2024-04-14 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_alter_homesection_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutsection',
            name='assuarance',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='aboutsection',
            name='content',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='aboutsection',
            name='value_proposition_1',
            field=models.CharField(max_length=130),
        ),
        migrations.AlterField(
            model_name='aboutsection',
            name='value_proposition_2',
            field=models.CharField(max_length=130),
        ),
        migrations.AlterField(
            model_name='aboutsection',
            name='value_proposition_3',
            field=models.CharField(max_length=130),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='contact',
            name='occupation',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone_number',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='homesection',
            name='content',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='homesection',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='newsandprojects',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='productssection',
            name='short_notes',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='team',
            name='description',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='team',
            name='role',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='testimonies',
            name='name_of_customer',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='testimonies',
            name='occupation',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='testimonies',
            name='testimony',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='valueproposition',
            name='header',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='valueproposition',
            name='short_notes',
            field=models.CharField(max_length=100),
        ),
    ]
