# Generated by Django 5.0.4 on 2024-04-14 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_alter_whymanitech_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonies',
            name='profile_image',
            field=models.ImageField(default='avatar.png', upload_to='manitech/images'),
        ),
    ]
