# Generated by Django 5.0.3 on 2024-08-02 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_projecttype_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_type',
            field=models.CharField(choices=[('Social', 'Social')], max_length=100),
        ),
        migrations.DeleteModel(
            name='ProjectType',
        ),
    ]
